main: "com.gmail.akashirt53072.newauctions.Main"
name: "NewAuctions"
version: "0.0.0"
api-version: "1.17"
commands:
  storage: 
    description: give storage item
    usage: /storage
    permission: newauction.normal
  auction:
    description: open auction
    usage: /auction
    permission: newauction.normal
  trade:
    description: send trade
    usage: /auction <player name>
    permission: newauction.normal
permissions:
  newauction.normal:
    description: all player
    default: true
  newauction.*:
    description: commands
    children:
      newauction.normal: true